language: erlang

env:
  - LUA=""

branches:
  only:
    - master

install:
  - sudo apt-get install luarocks
  - sudo luarocks install luaunit
  - sudo luarocks install mockagne
  - sudo luarocks install luabitop

script:
  - cd tests
  - $LUA tests.lua
